name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: 
          - ubuntu-24.04
          - ubuntu-22.04
          - windows-2022

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: conan-io/setup-conan@v1.2.0
        with:
          cache_packages: true

      - name: Build
        run: |
          conan build . --build=missing -s %:compiler.cppstd=20 -o export_compile_commands=True -o build_tests=True -o build_fuzzing=True

      - name: Test
        run: |
          ctest .