name: Documentation

on:
  push: 
    branches: 
      - 'master'
  tags:
    - 'v*'

jobs:
  build-docs:
    runs_on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          sudo apt install doxygen graphviz -y
          pip install mkdocs-material 