name: C++ Lint & Sanitizer

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
      - uses: conan-io/setup-conan@v1.2.0
        with:
          cache_packages: true

      - name: Install Conan Dependencies
        run: |
          conan profile detect -f
          conan install . --build=missing -s compiler.cppstd=20