name: C++ Lint & Sanitizer

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-type: [Debug]

    steps:
      - uses: actions/checkout@v3
      - uses: conan-io/setup-conan@v1.2.0
        with:
          cache_packages: true

      - name: Install Conan Dependencies
        run: |
          conan profile detect -f
          conan install . --build=missing -s build_type=${{ matrix.build-type }} -s compiler.cppstd=20

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} .. "-DCMAKE_CXX_CLANG_TIDY=/usr/bin/clang-tidy-3.9;--config-file=../.clang-tidy"