name: C++ Lint & Sanitizer

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write



    steps:
      - uses: actions/checkout@v3
      - uses: conan-io/setup-conan@v1.2.0
        with:
          cache_packages: true

      - uses: cpp-linter/cpp-linter-action@v2.16.4
        with:
          style: 'file'
          clang-tidy: '' # Use .clang-tidy file
          version: 21
          files-changed-only: false
          ignore: '|!cinfinity/**'
          thread-comments: 'true'
          cache-enable: true
          
      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1