name: C++ Lint & Sanitizer

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
      - uses: conan-io/setup-conan@v1.2.0
        with:
          cache_packages: true

      - name: Install Conan Dependencies
        run: |
          conan install . --build=missing -s compiler.cppstd=20

      - name: Build
      - run: |
          conan build .

      - name: Export Compile Commands
      - run: |
          cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - uses: cpp-linter/cpp-linter-action@v2.16.4
        with:
          style: 'file'
          extensions: 'c,h,cpp,hpp,inl'
          tidy-checks: '' # Use .clang-tidy file
          version: 21
          ignore: '|!cinfinity/**'
          files-changed-only: false
          cache-enable: true
          database: build