name: C++ Lint & Sanitizer

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-type: [Debug]

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake clang clang-tidy python3-pip clang-tools build-essential git
          pip3 install cpplint conan

      - name: Install Conan Dependencies
        run: |
          conan profile detect -f
          conan install . --build=missing -s build_type=${{ matrix.build-type }} -s compiler.cppstd=20

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} .. "-DCMAKE_CXX_CLANG_TIDY=/usr/bin/clang-tidy-3.9;--config-file=../.clang-tidy"